# Name of your pipeline
name: HelloWorldPipeline

# The trigger that starts the pipeline
trigger:
- main

# The job that the pipeline will perform
jobs:
  # The job for running the "Hello, World!" script
  - job: HelloWorld
    displayName: 'Hello, World!'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        echo 'Change Here'
      displayName: 'Print Hello, World!'
