name: Sample Pipeline

# Define the trigger for the pipeline
trigger:
  - main

# Define the stages of the pipeline
stages:
  - name: Build
    jobs:
      - name: Build Job
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
          - name: Build
            run: |
              # Insert build commands here

  - name: Test
    jobs:
      - name: Unit Test Job
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
          - name: Install Dependencies
            run: |
              # Insert dependency installation commands here
          - name: Run Unit Tests
            run: |

  - name: Push
    jobs:
      - name: Push Image
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
          - name: Push the image
            run: |
              # Insert build commands here
        
              


